apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# These resources together define the orderflow-web application.
resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - pdb.yaml
