apiVersion: v1
kind: Service

metadata:
  name: orderflow-web
  labels:
    app: orderflow-web

spec:
  # ClusterIP exposes the web application inside the cluster.
  # The AWS ALB/Ingress will handle external traffic.
  type: ClusterIP

  # Send traffic only to web pods managed by the Deployment.
  selector:
    app: orderflow-web

  ports:
    - name: http

      # Port exposed by the Kubernetes Service.
      port: 80

      # Port exposed by the web container.
      targetPort: http

      protocol: TCP
