apiVersion: v1
kind: ServiceAccount

metadata:
  name: order-api
  namespace: orderflow
  labels:
    app: order-api

---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: order-worker
  namespace: orderflow
  labels:
    app: order-worker
